{
 "title": "Showcase",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "core_id",
    "label": "Core ID",
    "query": "label_values(scaph_host_core_power_microwatts, core_id)"
   }
  ]
 },
 "panels": [
  { "title": "Power by Scope", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Host Power (microwatts)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "microwatts" }
   ],
   "targets": [
    { "expr": "scaph_host_power_microwatts", "legendFormat": "host active" },
    {
     "expr": "scaph_host_idle_power_microwatts",
     "legendFormat": "host idle"
    },
    {
     "expr": "scaph_host_activation_power_microwatts",
     "legendFormat": "host activation"
    },
    {
     "expr": "scaph_host_background_power_microwatts",
     "legendFormat": "host background"
    }
   ]
  },
  {
   "title": "Socket Power (microwatts)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "microwatts" }
   ],
   "targets": [
    { "expr": "scaph_socket_power_microwatts", "legendFormat": "socket {{socket_id}} active" },
    {
     "expr": "scaph_socket_idle_power_microwatts",
     "legendFormat": "socket {{socket_id}} idle"
    },
    {
     "expr": "scaph_socket_activation_power_microwatts",
     "legendFormat": "socket {{socket_id}} activation"
    },
    {
     "expr": "scaph_socket_background_power_microwatts",
     "legendFormat": "socket {{socket_id}} background"
    }
   ]
  },
  {
   "title": "Per-Core Power (microwatts)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "microwatts" }
   ],
   "targets": [
    {
     "expr": "scaph_host_core_power_microwatts",
     "legendFormat": "core {{core_id}}"
    }
   ]
  },
  { "title": "Per-Process Energy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Process Power (microwatts)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "microwatts" }
   ],
   "targets": [
    {
     "expr": "topk(10, scaph_process_power_consumption_microwatts)",
     "legendFormat": "{{cmdline}}"
    }
   ]
  },
  { "title": "Workload Core", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Workload Core",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "microwatts" }
   ],
   "targets": [
    {
     "expr": "scaph_host_core_power_microwatts{core_id=\"$core_id\"}",
     "legendFormat": "core $core_id"
    }
   ]
  }
 ]
}